
CREATE TABLE invoice_items(
  id INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
  unit_price  DECIMAL NOT NULL,
  quantity    INT NOT NULL,
  total_price DECIMAL NOT NULL,
  invoice_id  INT NOT NULL,
  treatment_id INT NOT NULL,
  FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (treatment_id) REFERENCES treatments(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE invoices(
  id INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
  total_amount DECIMAL NOT NULL,
  generated_at TIMESTAMP NOT NULL,
  payed_at     TIMESTAMP NOT NULL,
  medical_history__id INT NOT NULL,
  FOREIGN KEY (medical_history__id) REFERENCES medical_histories(id) ON DELETE RESTRICT ON UPDATE CASCADE,
);

